"""create emails and sync_state

Revision ID: 0001
Revises:
Create Date: 2026-09-24 13:43:04.350787
"""

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emails",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("sender", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("task", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emails_category"), "emails", ["category"], unique=False)
    op.create_index(op.f("ix_emails_date"), "emails", ["date"], unique=False)
    op.create_table(
        "sync_state",
        sa.Column("timeframe", sa.String(length=32), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("timeframe"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_state")
    op.drop_index(op.f("ix_emails_date"), table_name="emails")
    op.drop_index(op.f("ix_emails_category"), table_name="emails")
    op.drop_table("emails")
    # ### end Alembic commands ###
