"""student timetable and to-do fields

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-24 15:45:38.628910
"""
import sqlalchemy as sa

from alembic import op

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('instructor', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=7), server_default='#3b82f6', nullable=False),
    sa.Column('term_start', sa.Date(), nullable=True),
    sa.Column('term_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_slots_user_id'), 'class_slots', ['user_id'], unique=False)
    op.add_column('activities', sa.Column('priority', sa.Integer(), server_default='2', nullable=False))
    op.add_column('activities', sa.Column('course', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'course')
    op.drop_column('activities', 'priority')
    op.drop_index(op.f('ix_class_slots_user_id'), table_name='class_slots')
    op.drop_table('class_slots')
    # ### end Alembic commands ###
